check for writing in library after install

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -174,6 +174,17 @@ jobs:
           build_args: 'c("--compact-vignettes=gs+qpdf")'
         env:
           FULL_TEST_SUITE: 0
+      
+      - name: check that tests did not write anything to the R library
+        run: |
+          INSTALL_PATH=$(Rscript -e "cat(.libPaths()[1])")/XLConnect
+          INSTALLED_TIME=$(find "$INSTALL_PATH"/java -maxdepth 1 -type f -printf '%T@\n' | sort -n | tail -n 1 | awk '{print int($1+1)}' | xargs -I{} date -d "@{}" '+%Y-%m-%d %H:%M:%S')
+          WRITTEN_FILES=$(find "$INSTALL_PATH" -newermt "$INSTALLED_TIME" | wc -l)
+          if [[ $WRITTEN_FILES != 0 ]]; then
+              echo "Error! wrote to the library after installing!"
+              exit 1
+          fi
+
 
       - name: run complete test suite # some tests are not run in r check, as test xls(x) files are Rbuild-ignored
         if: always()
